### ISSUE TITLE
Issues in the checker tread exception

### ISSUE THREAD

**Issue by acocalypso** [georgeherby/MADevice#19]
I cloned the repo and follwed the steps. (Master branch)

After starting the main.py within the venv I got the following error:

`[09-25 20:46:49] [     ScanChecker] [         alert:96] [   ERROR] Issues in the checker tread exception was: Expecting ',' delimiter: line 9 column 41 (char 337)
`

I'm using python3.7 on Debian

Update: same for develop branch:

```
~/MADevice# py3/bin/python3.7 main.py
 [09-25 20:51:36] [     ScanChecker] [         alert:33] [    INFO] Starting Device Checker Script
Traceback (most recent call last):
  File "/root/MADevice/alert.py", line 36, in alert_thread
    servers_config_json = json.load(servers_json)
  File "/usr/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 9 column 41 (char 337)
 [09-25 20:51:36] [     ScanChecker] [         alert:101] [   ERROR] Issues in the checker tread exception was: Expecting ',' delimiter: line 9 column 41 (char 337)
 [09-25 20:51:41] [      MainThread] [           bot:22] [    INFO] Logged in. Username: BotStatus. User ID:xxxxxxxxxx
```

**Comment by georgeherby** [comment]
My guess is you are missing a `,` in your json

**Comment by acocalypso** [comment]
issue fixed i messed up the servers.json
